name: Fabio Angelini Portfolio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.88759
title: Work Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dedfe0'
    - '#cccccc'
    - '#ffffff'
    - '#aaaaaa'
    - '#808080'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
